# https://developer.crowdin.com/configuration-file/
# https://docusaurus.io/docs/i18n/crowdin

# CROWDIN CREDENTIALS
project_id: 114
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: '.'
base_url: 'https://joomla.crowdin.com'

'preserve_hierarchy': true

# skip_untranslated_strings – Only translated strings will be included in the exported translation files.
# skip_untranslated_files – Only translated files will be included in the exported translation archive.
# export_only_approved – Only texts that are both translated and approved will be included in the exported translation files.

files:
  # WEBSITE ELEMENTS
  - 'source': '/website_elements/help_pages_documentation/**/*'
    'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-help/%original_file_name%'
    'update_option': 'update_without_changes'

  - 'source': '/website_elements/user_documentation/**/*'
    'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/%original_file_name%'
    'update_option': 'update_without_changes'

  - 'source': '/website_elements/theme/**/*'
    'translation': '/i18n/%two_letters_code%/docusaurus-theme-classic/%original_file_name%'
    'update_option': 'update_without_changes'

  - 'source': '/website_elements/code.json'
    'translation': '/i18n/%two_letters_code%/%original_file_name%'
    'update_option': 'update_without_changes'

  # USER DOCUMENTATION
  - 'source': '/user_documentation/**/*'
    'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%'
    'update_option': 'update_without_changes'

  # HELP PAGES DOCUMENTATION
  - 'source': '/help_pages_documentation/**/*'
    'translation': '/i18n/%two_letters_code%/docusaurus-plugin-content-docs-help/**/%original_file_name%'
    'update_option': 'update_without_changes'
